// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.zwy.proto;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.zwy.proto.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string relaname = 2;</code>
   * @return The relaname.
   */
  String getRelaname();
  /**
   * <code>string relaname = 2;</code>
   * @return The bytes for relaname.
   */
  com.google.protobuf.ByteString
      getRelanameBytes();
}
